package com.efsf.sf.sql.entity;
// Generated 2013-07-29 13:34:29 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Branch generated by hbm2java
 */
@Entity
@Table(name="branch"
    ,catalog="SpolecznoscFinansowa"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Branch  implements java.io.Serializable {


     private Integer idBranch;
     private String name;
     private Set<Income> incomes = new HashSet<Income>(0);
     private Set<IncomeBuisnessActivity> incomeBuisnessActivities = new HashSet<IncomeBuisnessActivity>(0);

    public Branch() {
    }

	
    public Branch(String name) {
        this.name = name;
    }
    public Branch(String name, Set<Income> incomes, Set<IncomeBuisnessActivity> incomeBuisnessActivities) {
       this.name = name;
       this.incomes = incomes;
       this.incomeBuisnessActivities = incomeBuisnessActivities;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_branch", unique=true, nullable=false)
    public Integer getIdBranch() {
        return this.idBranch;
    }
    
    public void setIdBranch(Integer idBranch) {
        this.idBranch = idBranch;
    }
    
    @Column(name="name", unique=true, nullable=false, length=35)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="branch")
    public Set<Income> getIncomes() {
        return this.incomes;
    }
    
    public void setIncomes(Set<Income> incomes) {
        this.incomes = incomes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="branch")
    public Set<IncomeBuisnessActivity> getIncomeBuisnessActivities() {
        return this.incomeBuisnessActivities;
    }
    
    public void setIncomeBuisnessActivities(Set<IncomeBuisnessActivity> incomeBuisnessActivities) {
        this.incomeBuisnessActivities = incomeBuisnessActivities;
    }




}


