package com.efsf.sf.sql.entity;
// Generated 2013-08-01 09:42:02 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CaseRating generated by hbm2java
 */
@Entity
@Table(name = "caseRating")
public class CaseRating implements java.io.Serializable {

    private Integer idRating;
    private ClientCase clientCase;
    private Integer contact;
    private Integer culture;
    private Integer competence;
    private Integer punctuality;
    private Integer reliability;
    private Integer respect;
    private Integer difficulty;
    private Integer trust;
    private Double average;
    private String comment;
    private Date commentDate;

    public CaseRating() {
    }

    public CaseRating(ClientCase clientCase) {
        this.clientCase = clientCase;
    }


    @Id
    @Column(name = "id_rating", unique = true, nullable = false)
    @GeneratedValue(generator = "gen")
    @GenericGenerator(name = "gen", strategy = "foreign", parameters =
            @Parameter(name = "property", value = "clientCase"))
    public Integer getIdRating() {
        return this.idRating;
    }

    public void setIdRating(Integer idRating) {
        this.idRating = idRating;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public ClientCase getClientCase() {
        return this.clientCase;
    }

    public void setClientCase(ClientCase clientCase) {
        this.clientCase = clientCase;
    }

    @Column(name = "contact")
    public Integer getContact() {
        return this.contact;
    }

    public void setContact(Integer contact) {
        this.contact = contact;
    }

    @Column(name = "culture")
    public Integer getCulture() {
        return this.culture;
    }

    public void setCulture(Integer culture) {
        this.culture = culture;
    }

    @Column(name = "competence")
    public Integer getCompetence() {
        return this.competence;
    }

    public void setCompetence(Integer competence) {
        this.competence = competence;
    }

    @Column(name = "punctuality")
    public Integer getPunctuality() {
        return this.punctuality;
    }

    public void setPunctuality(Integer punctuality) {
        this.punctuality = punctuality;
    }

    @Column(name = "reliability")
    public Integer getReliability() {
        return this.reliability;
    }

    public void setReliability(Integer reliability) {
        this.reliability = reliability;
    }

    @Column(name = "respect")
    public Integer getRespect() {
        return this.respect;
    }

    public void setRespect(Integer respect) {
        this.respect = respect;
    }

    @Column(name = "difficulty")
    public Integer getDifficulty() {
        return this.difficulty;
    }

    public void setDifficulty(Integer difficulty) {
        this.difficulty = difficulty;
    }

    @Column(name = "trust")
    public Integer getTrust() {
        return this.trust;
    }

    public void setTrust(Integer trust) {
        this.trust = trust;
    }

    @Column(name = "average", precision = 22, scale = 0)
    public Double getAverage() {
        return this.average;
    }

    public void setAverage(Double average) {
        this.average = average;
    }

    @Column(name = "comment", length = 65535)
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "commentDate", length = 10)
    public Date getCommentDate() {
        return this.commentDate;
    }

    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }
}
