package com.efsf.sf.sql.entity;
// Generated 2013-08-01 09:42:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CaseStatus generated by hbm2java
 */
@Entity
@Table(name="caseStatus"
    ,catalog="SpolecznoscFinansowa"
)
public class CaseStatus  implements java.io.Serializable {


     private Integer idCaseStatus;
     private String name;
     private Set<ClientCase> clientCases = new HashSet<>(0);
     private Integer isActive=1;

    public CaseStatus() {
    }

    public CaseStatus(String name, Set<ClientCase> clientCases) {
       this.name = name;
       this.clientCases = clientCases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_caseStatus", unique=true, nullable=false)
    public Integer getIdCaseStatus() {
        return this.idCaseStatus;
    }
    
    public void setIdCaseStatus(Integer idCaseStatus) {
        this.idCaseStatus = idCaseStatus;
    }
    
    @Column(name="name", length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="caseStatus")
    public Set<ClientCase> getClientCases() {
        return this.clientCases;
    }
    
    public void setClientCases(Set<ClientCase> clientCases) {
        this.clientCases = clientCases;
    }


    public Integer getIsActive() {
        return isActive;
    }


    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }




}


