package com.efsf.sf.sql.entity;
// Generated 2013-07-29 13:21:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Education generated by hbm2java
 */
@Entity
@Table(name="education"
    ,catalog="SpolecznoscFinansowa"
)
public class Education  implements java.io.Serializable {


     private Integer idEducation;
     private String name;
     private Set<Client> clients = new HashSet<Client>(0);

    public Education() {
    }

    public Education(String name, Set<Client> clients) {
       this.name = name;
       this.clients = clients;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_education", unique=true, nullable=false)
    public Integer getIdEducation() {
        return this.idEducation;
    }
    
    public void setIdEducation(Integer idEducation) {
        this.idEducation = idEducation;
    }
    
    @Column(name="name", length=35)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="education")
    public Set<Client> getClients() {
        return this.clients;
    }
    
    public void setClients(Set<Client> clients) {
        this.clients = clients;
    }




}


