package com.efsf.sf.sql.entity;
// Generated 2013-08-01 09:42:02 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IdentyficationDocument generated by hbm2java
 */
@Entity
@Table(name = "identyficationDocument", uniqueConstraints =
        @UniqueConstraint(columnNames = "fk_client"))
public class IdentyficationDocument implements java.io.Serializable {

    private Integer idIdentyficationDocument;
    private Client client;
    private String kind;
    private String serial;
    private String number;
    private String deliveredBy;
    private Date expireDate;

    public IdentyficationDocument() {
    }

    public IdentyficationDocument(Client client) {
        this.client = client;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_identyficationDocument", unique = true, nullable = false)
    public Integer getIdIdentyficationDocument() {
        return this.idIdentyficationDocument;
    }

    public void setIdIdentyficationDocument(Integer idIdentyficationDocument) {
        this.idIdentyficationDocument = idIdentyficationDocument;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fk_client", unique = true, nullable = false)
    public Client getClient() {
        return this.client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    @Column(name = "kind", length = 25)
    public String getKind() {
        return this.kind;
    }

    public void setKind(String kind) {
        this.kind = kind;
    }

    @Column(name = "serial", length = 6)
    public String getSerial() {
        return this.serial;
    }

    public void setSerial(String serial) {
        this.serial = serial;
    }

    @Column(name = "number", length = 20)
    public String getNumber() {
        return this.number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    @Column(name = "deliveredBy", length = 120)
    public String getDeliveredBy() {
        return this.deliveredBy;
    }

    public void setDeliveredBy(String deliveredBy) {
        this.deliveredBy = deliveredBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "expireDate", length = 10)
    public Date getExpireDate() {
        return this.expireDate;
    }

    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }
}
