package com.efsf.sf.sql.entity;
// Generated 2013-08-01 09:42:02 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Income generated by hbm2java
 */
@Entity
@Table(name = "income")
public class Income implements java.io.Serializable {

    private Integer idIncome;
    private Client client;
    private EmploymentType employmentType;
    private Branch branch;
    private String employer;
    private BigDecimal monthlyNetto;
    private Date beginDate;

    public Income() {
    }

    public Income(Client client, EmploymentType employmentType, Branch branch) {
        this.client = client;
        this.employmentType = employmentType;
        this.branch = branch;
    }


    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_income", unique = true, nullable = false)
    public Integer getIdIncome() {
        return this.idIncome;
    }

    public void setIdIncome(Integer idIncome) {
        this.idIncome = idIncome;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fk_client", nullable = false)
    public Client getClient() {
        return this.client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fk_employmentType", nullable = false)
    public EmploymentType getEmploymentType() {
        return this.employmentType;
    }

    public void setEmploymentType(EmploymentType employmentType) {
        this.employmentType = employmentType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fk_branch", nullable = false)
    public Branch getBranch() {
        return this.branch;
    }

    public void setBranch(Branch branch) {
        this.branch = branch;
    }

    @Column(name = "employer")
    public String getEmployer() {
        return this.employer;
    }

    public void setEmployer(String employer) {
        this.employer = employer;
    }

    @Column(name = "monthlyNetto", precision = 8)
    public BigDecimal getMonthlyNetto() {
        return this.monthlyNetto;
    }

    public void setMonthlyNetto(BigDecimal monthlyNetto) {
        this.monthlyNetto = monthlyNetto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "beginDate", length = 10)
    public Date getBeginDate() {
        return this.beginDate;
    }

    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }
}
