package com.efsf.sf.sql.entity;
// Generated 2013-08-01 09:42:02 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InvoiceData generated by hbm2java
 */
@Entity
@Table(name = "invoiceData")
public class InvoiceData implements java.io.Serializable {

    private Integer idInvoieData;
    private Address address;
    private String name;
    private String nip;
    private String regon;

    public InvoiceData() {
    }

    public InvoiceData(Address address) {
        this.address = address;
    }

    public InvoiceData(Address address, String name, String nip, String regon) {
        this.address = address;
        this.name = name;
        this.nip = nip;
        this.regon = regon;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_invoieData", unique = true, nullable = false)
    public Integer getIdInvoieData() {
        return this.idInvoieData;
    }

    public void setIdInvoieData(Integer idInvoieData) {
        this.idInvoieData = idInvoieData;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fk_address", nullable = false)
    public Address getAddress() {
        return this.address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "nip", length = 45)
    public String getNip() {
        return this.nip;
    }

    public void setNip(String nip) {
        this.nip = nip;
    }

    @Column(name = "regon", length = 45)
    public String getRegon() {
        return this.regon;
    }

    public void setRegon(String regon) {
        this.regon = regon;
    }
}
