package com.efsf.sf.sql.entity;
// Generated 2013-08-01 09:42:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MaritalStatus generated by hbm2java
 */
@Entity
@Table(name="maritalStatus")
public class MaritalStatus  implements java.io.Serializable {


     private Integer idMaritalStatus;
     private String name;
     private Set<Client> clients = new HashSet<Client>(0);
     private Integer isActive=1;

    public MaritalStatus() {
    }

    public MaritalStatus(String name, Set<Client> clients) {
       this.name = name;
       this.clients = clients;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_maritalStatus", unique=true, nullable=false)
    public Integer getIdMaritalStatus() {
        return this.idMaritalStatus;
    }
    
    public void setIdMaritalStatus(Integer idMaritalStatus) {
        this.idMaritalStatus = idMaritalStatus;
    }
    
    @Column(name="name", length=55)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="maritalStatus")
    public Set<Client> getClients() {
        return this.clients;
    }
    
    public void setClients(Set<Client> clients) {
        this.clients = clients;
    }

    public Integer getIsActive() {
        return isActive;
    }

    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }




}


