package sql.entity;
// Generated 2013-06-27 14:28:15 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Kredyty generated by hbm2java
 */
@Entity
@Table(name="kredyty"
    ,catalog="System4"
)
public class Kredyty implements java.io.Serializable {
    
     private static final long serialVersionUID = 1L;

     private Integer kredytyId;
     private String nazwaBanku;
     private String nrUmowyPosrednictwa;
     private BigDecimal kwotaKredytuBrutto;
     private BigDecimal prowizjaBankuWprocentach;
     private BigDecimal prowizjaBankuWpln;
     private BigDecimal ubezpieczenieWpln;
     private BigDecimal kosztaWpln;
     private BigDecimal swotWprocentach;
     private BigDecimal swotWpln;
     private BigDecimal kwotaKonsolidacji;
     private Integer okresKredytowaniaWmc;
     private BigDecimal rataWpln;
     private BigDecimal oprocentowanieWprocentach;
     private BigDecimal wolnaGotowka;
     private String miejscePodpisaniaDokumentow;
     private Date dataMozliwegoUruchomienia;
     private Date dataDodaniaKredytu;
     private Boolean czyWygenerowanoDokumenty;
     private Set<KlienciKredyty> klienciKredyties = new HashSet<>(0);

    public Kredyty() {
    }

    public Kredyty(String nazwaBanku, String nrUmowyPosrednictwa, BigDecimal kwotaKredytuBrutto, BigDecimal prowizjaBankuWprocentach, BigDecimal prowizjaBankuWpln, BigDecimal ubezpieczenieWpln, BigDecimal kosztaWpln, BigDecimal swotWprocentach, BigDecimal swotWpln, BigDecimal kwotaKonsolidacji, Integer okresKredytowaniaWmc, BigDecimal rataWpln, BigDecimal oprocentowanieWprocentach, BigDecimal wolnaGotowka, String miejscePodpisaniaDokumentow, Date dataMozliwegoUruchomienia, Date dataDodaniaKredytu, Boolean czyWygenerowanoDokumenty, Set<KlienciKredyty> klienciKredyties) {
       this.nazwaBanku = nazwaBanku;
       this.nrUmowyPosrednictwa = nrUmowyPosrednictwa;
       this.kwotaKredytuBrutto = kwotaKredytuBrutto;
       this.prowizjaBankuWprocentach = prowizjaBankuWprocentach;
       this.prowizjaBankuWpln = prowizjaBankuWpln;
       this.ubezpieczenieWpln = ubezpieczenieWpln;
       this.kosztaWpln = kosztaWpln;
       this.swotWprocentach = swotWprocentach;
       this.swotWpln = swotWpln;
       this.kwotaKonsolidacji = kwotaKonsolidacji;
       this.okresKredytowaniaWmc = okresKredytowaniaWmc;
       this.rataWpln = rataWpln;
       this.oprocentowanieWprocentach = oprocentowanieWprocentach;
       this.wolnaGotowka = wolnaGotowka;
       this.miejscePodpisaniaDokumentow = miejscePodpisaniaDokumentow;
       this.dataMozliwegoUruchomienia = dataMozliwegoUruchomienia;
       this.dataDodaniaKredytu = dataDodaniaKredytu;
       this.czyWygenerowanoDokumenty = czyWygenerowanoDokumenty;
       this.klienciKredyties = klienciKredyties;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="kredyty_id", unique=true, nullable=false)
    public Integer getKredytyId() {
        return this.kredytyId;
    }
    
    public void setKredytyId(Integer kredytyId) {
        this.kredytyId = kredytyId;
    }
    
    @Column(name="nazwaBanku", length=60)
    public String getNazwaBanku() {
        return this.nazwaBanku;
    }
    
    public void setNazwaBanku(String nazwaBanku) {
        this.nazwaBanku = nazwaBanku;
    }
    
    @Column(name="nrUmowyPosrednictwa", length=30)
    public String getNrUmowyPosrednictwa() {
        return this.nrUmowyPosrednictwa;
    }
    
    public void setNrUmowyPosrednictwa(String nrUmowyPosrednictwa) {
        this.nrUmowyPosrednictwa = nrUmowyPosrednictwa;
    }
    
    @Column(name="kwotaKredytuBrutto", precision=12)
    public BigDecimal getKwotaKredytuBrutto() {
        return this.kwotaKredytuBrutto;
    }
    
    public void setKwotaKredytuBrutto(BigDecimal kwotaKredytuBrutto) {
        this.kwotaKredytuBrutto = kwotaKredytuBrutto;
    }
    
    @Column(name="prowizjaBankuWProcentach", precision=2)
    public BigDecimal getProwizjaBankuWprocentach() {
        return this.prowizjaBankuWprocentach;
    }
    
    public void setProwizjaBankuWprocentach(BigDecimal prowizjaBankuWprocentach) {
        this.prowizjaBankuWprocentach = prowizjaBankuWprocentach;
    }
    
    @Column(name="prowizjaBankuWPLN", precision=12)
    public BigDecimal getProwizjaBankuWpln() {
        return this.prowizjaBankuWpln;
    }
    
    public void setProwizjaBankuWpln(BigDecimal prowizjaBankuWpln) {
        this.prowizjaBankuWpln = prowizjaBankuWpln;
    }
    
    @Column(name="ubezpieczenieWPLN", precision=12)
    public BigDecimal getUbezpieczenieWpln() {
        return this.ubezpieczenieWpln;
    }
    
    public void setUbezpieczenieWpln(BigDecimal ubezpieczenieWpln) {
        this.ubezpieczenieWpln = ubezpieczenieWpln;
    }
    
    @Column(name="kosztaWPLN", precision=12)
    public BigDecimal getKosztaWpln() {
        return this.kosztaWpln;
    }
    
    public void setKosztaWpln(BigDecimal kosztaWpln) {
        this.kosztaWpln = kosztaWpln;
    }
    
    @Column(name="swotWprocentach", precision=2)
    public BigDecimal getSwotWprocentach() {
        return this.swotWprocentach;
    }
    
    public void setSwotWprocentach(BigDecimal swotWprocentach) {
        this.swotWprocentach = swotWprocentach;
    }
    
    @Column(name="swotWpln", precision=12)
    public BigDecimal getSwotWpln() {
        return this.swotWpln;
    }
    
    public void setSwotWpln(BigDecimal swotWpln) {
        this.swotWpln = swotWpln;
    }
    
    @Column(name="kwotaKonsolidacji", precision=12)
    public BigDecimal getKwotaKonsolidacji() {
        return this.kwotaKonsolidacji;
    }
    
    public void setKwotaKonsolidacji(BigDecimal kwotaKonsolidacji) {
        this.kwotaKonsolidacji = kwotaKonsolidacji;
    }
    
    @Column(name="okresKredytowaniaWmc")
    public Integer getOkresKredytowaniaWmc() {
        return this.okresKredytowaniaWmc;
    }
    
    public void setOkresKredytowaniaWmc(Integer okresKredytowaniaWmc) {
        this.okresKredytowaniaWmc = okresKredytowaniaWmc;
    }
    
    @Column(name="rataWPLN", precision=12)
    public BigDecimal getRataWpln() {
        return this.rataWpln;
    }
    
    public void setRataWpln(BigDecimal rataWpln) {
        this.rataWpln = rataWpln;
    }
    
    @Column(name="oprocentowanieWProcentach", precision=2)
    public BigDecimal getOprocentowanieWprocentach() {
        return this.oprocentowanieWprocentach;
    }
    
    public void setOprocentowanieWprocentach(BigDecimal oprocentowanieWprocentach) {
        this.oprocentowanieWprocentach = oprocentowanieWprocentach;
    }
    
    @Column(name="wolnaGotowka", precision=12)
    public BigDecimal getWolnaGotowka() {
        return this.wolnaGotowka;
    }
    
    public void setWolnaGotowka(BigDecimal wolnaGotowka) {
        this.wolnaGotowka = wolnaGotowka;
    }
    
    @Column(name="miejscePodpisaniaDokumentow", length=20)
    public String getMiejscePodpisaniaDokumentow() {
        return this.miejscePodpisaniaDokumentow;
    }
    
    public void setMiejscePodpisaniaDokumentow(String miejscePodpisaniaDokumentow) {
        this.miejscePodpisaniaDokumentow = miejscePodpisaniaDokumentow;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dataMozliwegoUruchomienia", length=10)
    public Date getDataMozliwegoUruchomienia() {
        return this.dataMozliwegoUruchomienia;
    }
    
    public void setDataMozliwegoUruchomienia(Date dataMozliwegoUruchomienia) {
        this.dataMozliwegoUruchomienia = dataMozliwegoUruchomienia;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dataDodaniaKredytu", length=10)
    public Date getDataDodaniaKredytu() {
        return this.dataDodaniaKredytu;
    }
    
    public void setDataDodaniaKredytu(Date dataDodaniaKredytu) {
        this.dataDodaniaKredytu = dataDodaniaKredytu;
    }
    
    @Column(name="czyWygenerowanoDokumenty")
    public Boolean getCzyWygenerowanoDokumenty() {
        return this.czyWygenerowanoDokumenty;
    }
    
    public void setCzyWygenerowanoDokumenty(Boolean czyWygenerowanoDokumenty) {
        this.czyWygenerowanoDokumenty = czyWygenerowanoDokumenty;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="id.kredyty")
    public Set<KlienciKredyty> getKlienciKredyties() {
        return this.klienciKredyties;
    }
    
    public void setKlienciKredyties(Set<KlienciKredyty> klienciKredyties) {
        this.klienciKredyties = klienciKredyties;
    }




}


